// Vercel Edge Middleware: serves the Markdown twin of a page when the client
// asks for it via `Accept: text/markdown` (acceptmarkdown.com content negotiation).
// The .md twins are generated at build time by scripts/generate-seo-files.mjs.
import { next } from '@vercel/edge';

export const config = {
  matcher: '/((?!assets/|sitemap\\.xml|robots\\.txt|llms\\.txt|.*\\..*).*)',
};

export default async function middleware(request) {
  const accept = request.headers.get('accept') || '';
  const wantsMarkdown = accept.includes('text/markdown');

  if (!wantsMarkdown) {
    return next({ headers: { Vary: 'Accept, Accept-Encoding' } });
  }

  const url = new URL(request.url);
  const mdPath = url.pathname === '/' ? '/index.md' : `${url.pathname}.md`;
  const mdResponse = await fetch(new URL(mdPath, url));

  if (mdResponse.ok) {
    return new Response(mdResponse.body, {
      status: 200,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        Vary: 'Accept, Accept-Encoding',
      },
    });
  }

  // No known page at this path — every real page has a .md twin (generated by
  // scripts/generate-seo-files.mjs), so a missing twin means the path is a 404.
  // Serve the markdown 404 body directly instead of the HTML 404 page.
  const md404 = await fetch(new URL('/404.md', url));
  if (md404.ok) {
    return new Response(md404.body, {
      status: 404,
      headers: {
        'Content-Type': 'text/markdown; charset=utf-8',
        Vary: 'Accept, Accept-Encoding',
      },
    });
  }

  return next({ headers: { Vary: 'Accept, Accept-Encoding' } });
}
